### Set up

In [1]:
import pandas as pd

### Load Bulk ATAC-seq file
location: `~/CSE185FinalProject/Figure_1e/data/GSE132440_ATAC_PeakNorm.txt`

In [2]:
ATAC = pd.read_csv('~/CSE185FinalProject/Figure_1e/data/GSE132440_ATAC_PeakNorm.txt',
                   sep="\t")
ATAC

,Peaks,D13_2_T1.Normal (C;RIK+PBS-d2),D7_3_T1.Normal (C;RIK+PBS-d2),D1_2_C-Ren-PBS-D2 -female-,D8_2_T2.Reg-ADM (C;RIK+Caer-d2),D8_3_T2.Reg-ADM (C;RIK+Caer-d2),D11_1_T2.Reg-ADM (C;RIK+Caer-d2),D14_2_C-Ren-C-d2 (ADM-shRen+),D6_1_C-Ren-C-d2 (ADM-shRen+),D6_3_T3.KrasG12D (KC;RIK+PBS-d2),...,D19_1_T4.Tum-ADR (KC;RIK+Caer-d2),D19_3_T4.Tum-ADR (KC;RIK+Caer-d2),D4_2_KC-REN-C-d2 (ADR-shRen+),D11_3_KC-552OFF-C-d2 (ADR-sh552Off),D2_1_T7.PDAC (KPflC-GEMMs),D12_1_T7.PDAC (KPcr_organoids),D12_2_T7.PDAC (KPcr_organoids),D22_3_T7.PDAC (KPcr_organoids),D3_2_T7.PDAC (KPR127H_shp53_orgs),D3_3_T7.PDAC (KPR127H_Ren_orgs)
0,chr1_3001656_3001961,13.419960,5.367960,11.504871,2.645634,4.317972,6.110474,6.988018,4.690510,6.218671,...,5.297277,2.788978,7.399043,2.088005,12.564510,4.917989,3.185094,13.584760,6.75689,13.294766
1,chr1_3109719_3110326,9.585685,19.324655,34.514614,14.550989,12.474142,13.748566,29.564693,10.051092,9.567187,...,9.837801,7.669690,4.708482,4.698010,3.769353,6.762235,9.555281,81.508557,10.61797,5.908785
2,chr1_3192412_3193073,1.917137,8.588735,13.805846,8.598312,7.676395,6.110474,10.213258,12.061311,7.175390,...,6.810785,4.880712,6.053762,6.264014,6.282255,6.762235,11.678677,9.056506,14.47905,38.407103
3,chr1_3239108_3239709,15.337097,6.441552,32.213640,14.550989,14.393240,11.711741,10.213258,18.091966,15.785858,...,13.621570,16.733870,14.125445,9.396021,26.385471,11.065476,30.789239,31.697772,21.23594,29.543925
4,chr1_3351007_3351367,21.088508,7.515144,32.213640,8.598312,9.115719,7.638092,10.213258,10.051092,10.045546,...,11.351308,11.155913,10.089604,8.874020,15.077412,6.147486,8.493583,18.113013,33.78445,14.771963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103932,chrY_499480_499864,17.254234,9.662327,2.300974,5.291269,13.433691,14.766978,10.750798,16.751820,22.482889,...,33.297171,23.706315,37.667853,28.188062,28.898373,3.073743,6.370187,4.528253,0.96527,1.477196
103933,chrY_516124_516641,9.585685,8.588735,2.300974,5.952677,3.838197,7.128886,10.213258,2.010218,8.132109,...,22.702617,5.577957,32.286731,24.012053,17.590314,1.229497,3.185094,9.056506,0.96527,1.477196
103934,chrY_581156_582843,191.713707,122.389481,4.601949,142.202849,95.954936,106.424086,122.021553,137.364926,112.892803,...,116.540098,147.118603,113.676200,119.538263,98.003177,111.884252,32.912635,58.867291,0.96527,1.477196
103935,chrY_608935_609561,13.419960,6.441552,2.300974,8.598312,11.994367,10.184123,13.976037,8.710947,21.047811,...,17.405339,24.403560,22.869768,22.446049,25.129020,1.229497,2.123396,9.056506,1.93054,1.477196
103936,chrY_622075_623340,159.122377,142.787728,6.902923,141.541440,114.666148,120.681858,131.159731,163.497766,118.633115,...,124.107637,165.246962,138.563888,119.016262,96.746726,103.277771,28.665844,58.867291,0.96527,1.477196

In [3]:
rename = {
     "D1_2_C-Ren-PBS-D2 -female-": "Normal_ATAC1",
     "D13_2_T1.Normal (C;RIK+PBS-d2)": "Normal_ATAC2",
     "D7_3_T1.Normal (C;RIK+PBS-d2)": "Normal_ATAC3", 
     "D11_1_T2.Reg-ADM (C;RIK+Caer-d2)": "Injury_ATAC1",  
     "D14_2_C-Ren-C-d2 (ADM-shRen+)": "Injury_ATAC2",  
     "D6_1_C-Ren-C-d2 (ADM-shRen+)": "Injury_ATAC3",  
     "D8_2_T2.Reg-ADM (C;RIK+Caer-d2)": "Injury_ATAC4",  
     "D8_3_T2.Reg-ADM (C;RIK+Caer-d2)": "Injury_ATAC5",  
     "D13_3_T3.KrasG12D (KC;RIK+PBS-d2)": "Kras_ATAC1",  
     "D6_3_T3.KrasG12D (KC;RIK+PBS-d2)": "Kras_ATAC2",  
     "D8_1_T3.KrasG12D (KC;RIK+PBS-d2)": "Kras_ATAC3", 
     "D11_3_KC-552OFF-C-d2  (ADR-sh552Off)": "KrasInjury_ATAC1",  
     "D18_3_T4.Tum-ADR (KC;RIK+Caer-d2)": "KrasInjury_ATAC2",  
     "D19_3_T4.Tum-ADR (KC;RIK+Caer-d2)": "KrasInjury_ATAC3",  
     "D4_2_KC-REN-C-d2 (ADR-shRen+)": "KrasInjury_ATAC4",  
     "D7_1_T4.Tum-ADR (KC;RIK+Caer-d2)": "KrasInjury_ATAC5",  
     "D19_1_T4.Tum-ADR (KC;RIK+Caer-d2)": "KrasInjury_ATAC6",  
     "D2_1_T7.PDAC (KPflC-GEMMs)": "PDAC_ATAC1",  
     "D12_1_T7.PDAC (KPcr_organoids)": "PDAC_ATAC2",  
     "D12_2_T7.PDAC (KPcr_organoids)": "PDAC_ATAC3", 
     "D22_3_T7.PDAC (KPcr_organoids)": "PDAC_ATAC4",
     "D3_2_T7.PDAC (KPR127H_shp53_orgs)": "PDAC_ATAC5",
     "D3_3_T7.PDAC (KPR127H_Ren_orgs)": "PDAC_ATAC6"
}

ATAC.rename(columns=rename, inplace=True)
ATAC.columns

Index(['Peaks', 'Normal_ATAC2', 'Normal_ATAC3', 'Normal_ATAC1', 'Injury_ATAC4',
       'Injury_ATAC5', 'Injury_ATAC1', 'Injury_ATAC2', 'Injury_ATAC3',
       'Kras_ATAC2', 'Kras_ATAC3', 'Kras_ATAC1', 'KrasInjury_ATAC5',
       'KrasInjury_ATAC2', 'KrasInjury_ATAC6', 'KrasInjury_ATAC3',
       'KrasInjury_ATAC4', 'KrasInjury_ATAC1', 'PDAC_ATAC1', 'PDAC_ATAC2',
       'PDAC_ATAC3', 'PDAC_ATAC4', 'PDAC_ATAC5', 'PDAC_ATAC6'],
      dtype='object')

### Load Bulk RNA-seq (Set 1)
location: `data/Bulk_RNA-seq/GSE132326_Alonso-Curbelo_RNASeq_SET1.csv`

In [4]:
RNA = pd.read_csv('data/Bulk_RNA-seq/GSE132326_Alonso-Curbelo_RNASeq_SET1.csv')
RNA

,ID,Normal_RNA1,Normal_RNA2,Normal_RNA3,Normal_RNA4,RegADM_RNA1,RegADM_RNA2,RegADM_RNA3,RegADM_RNA4,RegADM_RNA5,...,PDAC_RNA1,PDAC_RNA2,PDAC_RNA3,Gene_name,chromosome_name,start_position,end_position,transcript_length,Strand,Karyotype_band
0,ENSMUSG00000000001,41,119,94,21,176,225,436,238,242,...,1532,1387,1357,Gnai3,3,108107280,108146146,3262,-,F2.3
1,ENSMUSG00000000003,0,0,0,0,0,0,0,0,0,...,0,0,0,Pbsn,X,77837901,77853623,902,-,B
2,ENSMUSG00000000028,2,2,1,7,6,7,29,18,12,...,168,53,111,Cdc45,16,18780447,18811987,2143,-,A3
3,ENSMUSG00000000031,0,3,5,5,207,48,142,48,263,...,420,255,296,H19,7,142575529,142578143,2286,-,F5
4,ENSMUSG00000000037,0,0,0,0,0,1,1,1,2,...,8,1,4,Scml2,X,161117193,161258213,4847,+,F4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53460,ENSMUSG00000115846,0,0,0,0,0,0,0,0,0,...,0,0,0,AC107711.6,14,45541173,45543567,1088,-,C1
53461,ENSMUSG00000115847,0,0,0,0,0,0,0,0,0,...,0,0,0,AC109172.2,14,82855964,82856344,381,-,D3
53462,ENSMUSG00000115848,0,0,0,0,0,0,0,0,0,...,1,0,0,AC114008.2,15,37171058,37172404,1347,-,B3.1
53463,ENSMUSG00000115849,0,0,0,0,0,0,0,0,0,...,4,0,0,AC156016.5,14,47261832,47262186,355,-,C1
53464,ENSMUSG00000115850,0,0,0,0,0,0,0,0,0,...,0,0,0,AC118639.2,15,25414637,25445640,223,-,B1

In [26]:
RNA_region = RNA[["ID","chromosome_name",
                  "start_position","end_position"]]
RNA_region.head()

                   ID chromosome_name  start_position  end_position
0  ENSMUSG00000000001               3       108107280     108146146
1  ENSMUSG00000000003               X        77837901      77853623
2  ENSMUSG00000000028              16        18780447      18811987
3  ENSMUSG00000000031               7       142575529     142578143
4  ENSMUSG00000000037               X       161117193     161258213

### Due to time, instead of doing the integrative analysis, just use the extended table 5

In [19]:
integrative = pd.read_excel("data/41586_2020_3147_MOESM7_ESM.xlsx",
                            sheet_name="KrasG12DInjury_vs_Normal", index_col=0)
integrative.dropna(inplace=True)

In [25]:
integrative.head()

,ID,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ATAC-RNA_status
Gene_name,,,,,,,,
Prss22,ENSMUSG00000045027,175.999100,9.181689,1.186109,7.741015,9.862618e-15,3.491408e-13,ATAC-GAIN_UP
Chil4,ENSMUSG00000063779,187.038667,8.954918,1.758181,5.093286,3.519095e-07,3.742030e-06,ATAC-GAIN_UP
Anxa10,ENSMUSG00000031635,245.590307,8.709109,1.081537,8.052531,8.109935e-16,3.381342e-14,ATAC-GAIN_UP
Areg,ENSMUSG00000029378,201.135591,8.656658,1.178385,7.346204,2.039145e-13,5.885984e-12,ATAC-GAIN_UP
Areg,ENSMUSG00000029378,201.135591,8.656658,1.178385,7.346204,2.039145e-13,5.885984e-12,ATAC-GAIN_UP

In [24]:
integrative.isnull().any()

ID                 False
baseMean           False
log2FoldChange     False
lfcSE              False
stat               False
pvalue             False
padj               False
ATAC-RNA_status    False
dtype: bool

In [28]:
integrative_region = pd.merge(left=integrative, right=RNA_region, how='left',
                              left_on='ID', right_on='ID')
integrative_region.head()

,ID,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ATAC-RNA_status,chromosome_name,start_position,end_position
0,ENSMUSG00000045027,175.999100,9.181689,1.186109,7.741015,9.862618e-15,3.491408e-13,ATAC-GAIN_UP,17,23993535,23998100
1,ENSMUSG00000063779,187.038667,8.954918,1.758181,5.093286,3.519095e-07,3.742030e-06,ATAC-GAIN_UP,3,106201490,106219507
2,ENSMUSG00000031635,245.590307,8.709109,1.081537,8.052531,8.109935e-16,3.381342e-14,ATAC-GAIN_UP,8,62057042,62123150
3,ENSMUSG00000029378,201.135591,8.656658,1.178385,7.346204,2.039145e-13,5.885984e-12,ATAC-GAIN_UP,5,91139599,91148432
4,ENSMUSG00000029378,201.135591,8.656658,1.178385,7.346204,2.039145e-13,5.885984e-12,ATAC-GAIN_UP,5,91139599,91148432

In [29]:
integrative_region.isnull().any()

ID                 False
baseMean           False
log2FoldChange     False
lfcSE              False
stat               False
pvalue             False
padj               False
ATAC-RNA_status    False
chromosome_name    False
start_position     False
end_position       False
dtype: bool

In [45]:
integrative_region_bed = {"chrom": [],
                          "start_position": [], 
                          "end_position": []}

for chrom, start, end in zip(integrative_region.chromosome_name,
                             integrative_region.start_position,
                             integrative_region.end_position):
    
    integrative_region_bed["chrom"].append("chr" + str(chrom))
    integrative_region_bed["start_position"].append(start)
    integrative_region_bed["end_position"].append(end)

integrative_region_BED_df = pd.DataFrame(integrative_region_bed)
integrative_region_BED_df = integrative_region_BED_df.set_index("chrom")
integrative_region_BED_df.head()

       start_position  end_position
chrom
chr17        23993535      23998100
chr3        106201490     106219507
chr8         62057042      62123150
chr5         91139599      91148432
chr5         91139599      91148432

In [46]:
# create a pseudo bed file based on integrate information
integrative_region_BED_df.to_csv('data/integrative.bed', sep="\t")

### The pseudo bed for scATACseq

In [33]:
import scanpy as scanpy

In [34]:
adata = scanpy.read_10x_h5("data/scATAC-seq/GSE137069_Merged_filtered_peak_bc_matrix.h5",
                           genome=None, gex_only=False)

In [38]:
scATAC = pd.DataFrame(adata.var)
scATAC.head()

                                  gene_ids feature_types genome
chr1:3493532-3494115  chr1:3493532-3494115         Peaks   mm10
chr1:3514498-3515608  chr1:3514498-3515608         Peaks   mm10
chr1:3534683-3535113  chr1:3534683-3535113         Peaks   mm10
chr1:3535378-3535755  chr1:3535378-3535755         Peaks   mm10
chr1:3551128-3551665  chr1:3551128-3551665         Peaks   mm10

In [43]:
scATAC_bed = {"chrom": [],
              "start_position":[],
              "end_position":[]}

for gene_ids in scATAC.gene_ids:
    chrom_region = gene_ids.split(":")
    chrom = chrom_region[0]
    region = chrom_region[1]
    
    start_end = region.split("-")
    start = start_end[0]
    end = start_end[1]
    
    scATAC_bed["chrom"].append(chrom)
    scATAC_bed["start_position"].append(start)
    scATAC_bed["end_position"].append(end)
    
scATAC_BED_df = pd.DataFrame(scATAC_bed)
scATAC_BED_df = scATAC_BED_df.set_index("chrom")
scATAC_BED_df.head()

      start_position end_position
chrom
chr1         3493532      3494115
chr1         3514498      3515608
chr1         3534683      3535113
chr1         3535378      3535755
chr1         3551128      3551665

In [44]:
# create a pseudo bed file based on scATACseq information
scATAC_BED_df.to_csv('data/scATAC.bed', sep="\t")

## Find motif
- AP-1: AP-1(bZIP)/ThioMac-PU.1-ChIP-Seq [GSM537983](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM537983)
- NR5A2: [GSM846875](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM846875)

### For NR5A2:

__Homer__
1. get start
```shell
# for input
makeTagDirectory ~/CSE185FinalProject/Figure_4e\&f/data/tagdirs/input ~/CSE185FinalProject/Figure_4e\&f/data/GSM846874_AlnInput.txt
# for NR5a2
makeTagDirectory ~/CSE185FinalProject/Figure_4e\&f/data/tagdirs/NR5a2 ~/CSE185FinalProject/Figure_4e\&f/data/GSM846875_AlnNR5a2ChIP.txt
```
2. find peak
```shell
findPeaks ~/CSE185FinalProject/Figure_4e\&f/data/tagdirs/NR5a2 -i ~/CSE185FinalProject/Figure_4e\&f/data/tagdirs/input -style factor -o auto
```
3. convert to bed 
```shell
pos2bed.pl ~/CSE185FinalProject/Figure_4e\&f/data/tagdirs/NR5a2/peaks.txt > ~/CSE185FinalProject/Figure_4e\&f/data/NR5a2.peaks.bed
```

#### Motif data location
- AP-1: `~/CSE185FinalProject/Figure_4e\&f/data/GSM537983_Sample1.ThioMac-PU.1.bed`
- NR5a2: `~/CSE185FinalProject/Figure_4e\&f/data/NR5a2.peaks.bed`

### Intersection with integrative location
```shell
# for AP-1
intersectBed -wa \
               -a ~/CSE185FinalProject/Figure_4e\&f/data/integrative.bed \
               -b ~/CSE185FinalProject/Figure_4e\&f/data/GSM537983_Sample1.ThioMac-PU.1.bed \
> ~/CSE185FinalProject/Figure_4e\&f/data/integrative_AP-1.bed

# for NR5a2
intersectBed -wa \
               -a ~/CSE185FinalProject/Figure_4e\&f/data/integrative.bed \
               -b ~/CSE185FinalProject/Figure_4e\&f/data/NR5a2.peaks.bed \
> ~/CSE185FinalProject/Figure_4e\&f/data/integrative_NR5a2.bed
```

### lift over to mm10
https://genome.ucsc.edu/cgi-bin/hgLiftOver

__lifted file location__
- AP-1: `~/CSE185FinalProject/Figure_4e\&f/data/hglft_genome_integrative_AP-1.bed`
- NR5a2: `~/CSE185FinalProject/Figure_4e\&f/data/hglft_genome_integrative_NR5a2.bed`

### Intersection with integrative location
```shell
# for AP-1
intersectBed -wa \
               -a ~/CSE185FinalProject/Figure_4e\&f/data/scATAC.bed \
               -b ~/CSE185FinalProject/Figure_4e\&f/data/hglft_genome_integrative_AP-1.bed \
               -f 1.0 \
> ~/CSE185FinalProject/Figure_4e\&f/data/scATAC_AP-1.bed

# for NR5a2
intersectBed -wa \
               -a ~/CSE185FinalProject/Figure_4e\&f/data/scATAC.bed \
               -b ~/CSE185FinalProject/Figure_4e\&f/data/hglft_genome_integrative_NR5a2.bed \
               -f 1.0 \
> ~/CSE185FinalProject/Figure_4e\&f/data/scATAC_NR5a2.bed
```